import React from 'react';

const AIDisclaimer = ({ aiGenerated }) => {
  if (!aiGenerated) return null;
  
  return (
    <div className="mt-4 p-3 bg-gray-50 border border-gray-200 rounded-md text-sm text-gray-500 text-center shadow-sm">
      <span className="font-medium">⚠️ This result was generated by an AI model.</span> Verify with a licensed pharmacist before administering.
    </div>
  );
};

export default AIDisclaimer;
