/**
 * Token storage for the PWA (main thread and service worker).
 *
 * Design (audit S19):
 *  - The JWT is never written to localStorage (readable by any script, persisted in clear text).
 *  - It is encrypted with an AES-GCM key generated by WebCrypto with `extractable: false` and
 *    stored as a CryptoKey object in IndexedDB. The browser will not export that key, so a copied
 *    IndexedDB file cannot be decrypted elsewhere.
 *  - Limits: script running in this origin (XSS) can still ask the browser to decrypt. The real
 *    defences are CSP, short token lifetimes and no third-party script. This is defence in depth.
 */
const DB_NAME = 'PharmaTraceSecure';
const DB_VERSION = 1;
const STORE = 'kv';
const KEY_ID = 'token-key';
const TOKEN_ID = 'token';

function openDb() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => req.result.createObjectStore(STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idb(mode, fn) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE, mode);
    const result = fn(tx.objectStore(STORE));
    tx.oncomplete = () => resolve(result?.result ?? result);
    tx.onerror = () => reject(tx.error);
  });
}

async function getKey() {
  const existing = await idb('readonly', (s) => s.get(KEY_ID));
  if (existing) return existing;
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
  await idb('readwrite', (s) => s.put(key, KEY_ID));
  return key;
}

export async function storeEncryptedTokenInIndexedDB(token) {
  if (!token) return clearStoredToken();
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const data = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await getKey(), new TextEncoder().encode(token));
  await idb('readwrite', (s) => s.put({ iv, data }, TOKEN_ID));
}

export async function getDecryptedTokenFromIndexedDB() {
  try {
    const rec = await idb('readonly', (s) => s.get(TOKEN_ID));
    if (!rec) return null;
    const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: rec.iv }, await getKey(), rec.data);
    return new TextDecoder().decode(plain);
  } catch {
    return null; // corrupted or key rotated: treat as signed out
  }
}

export async function clearStoredToken() {
  try {
    await idb('readwrite', (s) => s.delete(TOKEN_ID));
  } catch {
    /* nothing stored */
  }
}
